// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw5Afkh_P2ewMnI4YXcLsP_IMJUWVDSRA',
    appId: '1:187973614750:web:da18389493cf0e7f2d4f8f',
    messagingSenderId: '187973614750',
    projectId: 'gubovoso',
    authDomain: 'gubovoso.firebaseapp.com',
    storageBucket: 'gubovoso.appspot.com',
    measurementId: 'G-Q3YJN083R0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6m2AhbiX11lhZfdYGXqzBeE7aZBRaYHo',
    appId: '1:187973614750:android:70fd9f13cf3e5e522d4f8f',
    messagingSenderId: '187973614750',
    projectId: 'gubovoso',
    storageBucket: 'gubovoso.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1p1m28X4wfNjKnRQwYjeml_2Sx_v6_fo',
    appId: '1:187973614750:ios:007f6171a0d7e4cc2d4f8f',
    messagingSenderId: '187973614750',
    projectId: 'gubovoso',
    storageBucket: 'gubovoso.appspot.com',
    iosBundleId: 'com.example.guvoboso',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1p1m28X4wfNjKnRQwYjeml_2Sx_v6_fo',
    appId: '1:187973614750:ios:007f6171a0d7e4cc2d4f8f',
    messagingSenderId: '187973614750',
    projectId: 'gubovoso',
    storageBucket: 'gubovoso.appspot.com',
    iosBundleId: 'com.example.guvoboso',
  );
}
